requires 'perl', '>= 5.10.1';

requires 'Catmandu::DBI',0;
requires 'Catmandu',0;
requires 'Crypt::OpenSSL::RSA',0;
requires 'Dancer',0;
requires 'Data::UUID',0;
requires 'DBD::SQLite',0;
requires 'JSON',0;
requires 'LWP::Protocol::https',0;
requires 'LWP::UserAgent',0;
requires 'Moo',0;
requires 'Path::Tiny',0;
requires 'Plack',0;
requires 'YAML',0;
